"""
Django settings for errand project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv  # pip install python-dotenv
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# load .env located in project root (next to manage.py)
load_dotenv(BASE_DIR / ".env")

# Paystack
PAYSTACK_PUBLIC_KEY = os.getenv("PAYSTACK_PUBLIC_KEY")
PAYSTACK_SECRET_KEY = os.getenv("PAYSTACK_SECRET_KEY")
PAYSTACK_BASE_URL = os.getenv("PAYSTACK_BASE_URL", "https://api.paystack.co")

# When running tests or in CI you may want to fake Paystack calls instead of
# making real HTTP requests. Set the environment variable PAYSTACK_FAKE_IN_TESTS
# to a truthy value (1/true/yes) to enable the fake path. Default is False.
PAYSTACK_FAKE_IN_TESTS = os.getenv("PAYSTACK_FAKE_IN_TESTS", "False").lower() in ("1", "true", "yes")

# Default platform deposit VDA/instructions (used to show where creators should send
# money when posting errands). You can override these in production with real values.
PAYSTACK_DEPOSIT_INSTRUCTIONS = {
    "account_number": os.getenv("PLATFORM_VDA_ACCOUNT_NUMBER", "0000000000"),
    "bank_name": os.getenv("PLATFORM_VDA_BANK", "TestBank"),
    "account_name": os.getenv("PLATFORM_VDA_ACCOUNT_NAME", "Errand Platform"),
    "reference": os.getenv("PLATFORM_VDA_REFERENCE", "PLATFORMVDA1"),
}

# sanity check during development
if not PAYSTACK_SECRET_KEY:
    # don't crash in production automatically; this is just a helpful dev check
    raise RuntimeError("PAYSTACK_SECRET_KEY not set in environment")


# Illegal keywords to check when users create errands via the web form.
# Move here to allow tuning without editing view code.
ILLEGAL_KEYWORDS = [
    "drugs",
    "cocaine",
    "heroin",
    "meth",
    "weapon",
    "weapons",
    "gun",
    "firearm",
    "bomb",
    "explosive",
    "kill",
    "murder",
    "assault",
    "steal",
    "fraud",
    "hack",
    "illegal",
]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--i#io&2a^4^up5ai6)+*nqq_%@fw(5o9zh+%vd)4$uebu+4htn'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
ALLOWED_HOSTS = ["localhost", "127.0.0.1", "testserver"]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.BasicAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
}

# Use our custom backend which authenticates against the local Customer model.
AUTHENTICATION_BACKENDS = [
    "user.backends.CustomerBackend",
]

# Application definition

INSTALLED_APPS = [
    'user',
    'errands',
    'payment',
    'rest_framework',
    'django.contrib.humanize',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'errand.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'errand.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Serve project-level static/ during development (helps the CSS placed at /static/)
STATICFILES_DIRS = [
    str(BASE_DIR / "static"),
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
