# Generated by Django 5.2.7 on 2025-11-09 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_num', models.CharField(max_length=10)),
                ('bank_name', models.CharField()),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone_num', models.CharField(max_length=11)),
                ('vda_account_number', models.CharField(blank=True, max_length=20, null=True)),
                ('vda_bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('vda_account_name', models.CharField(blank=True, max_length=100, null=True)),
                ('vda_reference', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='user.customer')),
            ],
        ),
    ]
